import "../nikola.css";

const career = [
  { period: "2022.10. – present", role: "Deputy County Clerk", org: "Bács-Kiskun County Self-Government Office", text: "Legal, organisational and administrative responsibilities, preparation for General Assembly meetings, funding and procurement matters, and regional coordination." },
  { period: "2020.02. – 2022.10.", role: "Municipal Clerk", org: "Municipal Office of Jászkarajenő", text: "Management of the municipal office, organisational and institutional development, and legal oversight of projects." },
  { period: "2021.03. – 2022.09.", role: "Managing Director", org: "Jászkarajenői Szolgáltató Nonprofit Kft.", text: "Management of a municipally owned company, operations, and project management." },
  { period: "2020.03. – present", role: "Bar-registered Legal Counsel", org: "Kecskemét Bar Association", text: "Legal representation and advisory services, including representation in litigation." },
  { period: "2017.01. – 2020.01.", role: "Legal Adviser", org: "Bács-Kiskun County Government Office", text: "Legality reviews, compliance, and executive support." },
  { period: "2006.02. – 2016.12.", role: "Legal Adviser, Application Specialist", org: "Agricultural and Rural Development Agency (MVH)", text: "Administrative review of EU and national agricultural aid schemes and adjudication of legal remedy applications." },
];

const areas = [["PUBLIC ADMINISTRATION", "AND LOCAL GOVERNMENT"], ["EU FUNDING", "AND PROJECTS"], ["PUBLIC PROCUREMENT", "AND COMPLIANCE"], ["LEGAL ADVISORY", "AND REPRESENTATION"], ["ORGANISATION", "AND COLLABORATION"]] as const;

export default function NikolaEnglishPage() {
  return <div className="nikola-viewport">
    <main className="nikola-page">
      <nav className="nikola-nav" aria-label="Main navigation"><a className="monogram" href="https://svircevic.hu">SN</a><div className="nav-links"><a href="#about">ABOUT ME</a><a href="#career">CAREER</a><a href="#areas">PROFESSIONAL AREAS</a><a href="#publications">PUBLICATIONS</a><a href="#contact">CONTACT</a></div><div className="nav-lang"><span /> <a href="https://nikola.svircevic.hu">HU</a> <b>|</b> <a href="https://nikola.svircevic.hu/en">EN</a></div></nav>
      <section className="nikola-hero"><div className="hero-photo"><img src="/images/nikola-hero-reference.png" alt="Dr. Svircevic Nikola" /></div><div className="hero-copy"><span className="eyebrow">DR.</span><h1>SVIRCEVIC<br />NIKOLA</h1><div className="gold-rule" /><div className="qualification">LAWYER &amp; ECONOMIST</div><p>For more than twenty years, I have worked in legal and public administration roles. Throughout my career, I have gained experience in local government, regional public administration and specialist assignments. My professional interests include public administration, law, economic interrelationships, EU funding and public procurement.</p><div className="hero-actions"><a className="primary" href="#about">ABOUT ME →</a><a className="secondary" href="#contact">CONTACT</a></div></div></section>
      <section className="expertise-strip" aria-label="Professional focus"><SkillItem kind="book" top="LEGAL" bottom="EXPERTISE" /><SkillItem kind="document" top="PUBLIC ADMIN." bottom="EXPERIENCE" /><SkillItem kind="layers" top="PROJECTS" bottom="AND FUNDING" /><SkillItem kind="handshake" top="PUBLIC PROCUREMENT" bottom="AND COMPLIANCE" /><SkillItem kind="people" top="COLLABORATION" bottom="AND ORGANISATION" /></section>
      <section className="about-section" id="about"><div className="about-copy"><SectionTitle title="ABOUT ME" /><p>I am a lawyer and economist with more than twenty years of experience across different levels of public administration. My background includes local government, regional public administration and specialist assignments.</p><p>In my work, I consider it important to combine legal and economic perspectives, ensure regulated and transparent operations, and support the effective implementation of projects and developments.</p><div className="stats"><Stat number="20+" label="years of professional experience" /><Stat number="3" label="levels of public administration experience" /><Stat number="4" label="years of project management experience" /><Stat number="2" label="years of corporate management experience" /></div></div><div className="about-photo"><img src="/images/nikola-conference-original.jpg" alt="Dr. Svircevic Nikola" /></div></section>
      <section className="career-section" id="career"><div className="career-main"><SectionTitle title="CAREER" /><div className="timeline">{career.map((item) => <div className="career-item" key={`${item.period}-${item.role}`}><div className="period">{item.period}</div><div><h3>{item.role}</h3><strong>{item.org}</strong><p>{item.text}</p></div></div>)}</div></div><aside className="quote-panel" aria-label="Quote"><div className="quote-content"><div className="quote-mark">„</div><p>Law, public administration and an economic perspective complement one another to provide real solutions to the challenges of everyday work.</p><div className="gold-rule" /></div></aside></section>
      <section className="areas-section" id="areas"><SectionTitle title="PROFESSIONAL AREAS" dark /><div className="areas-grid">{areas.map(([a,b]) => <article key={a}><div className="area-image" aria-hidden="true" /><h3><span>{a}</span><span>{b}</span></h3></article>)}</div></section>
      <footer className="nikola-footer" id="contact"><span><a className="footer-home" href="https://svircevic.hu">← BACK TO HOMEPAGE</a><span className="footer-name">DR. SVIRCEVIC NIKOLA</span></span><span className="footer-rule" /><span>KECSKEMÉT</span><span>|</span><a className="footer-linkedin" id="publications" href="https://www.linkedin.com/in/nikola-svircevic" target="_blank" rel="noopener noreferrer" aria-label="LinkedIn profile">in</a></footer>
    </main>
  </div>;
}

function SectionTitle({ title, dark = false }: { title: string; dark?: boolean }) { return <div className={`section-title${dark ? " dark" : ""}`}><h2>{title}</h2><span /></div>; }
function Stat({ number, label }: { number: string; label: string }) { return <div className="stat"><strong>{number}</strong><span>{label}</span></div>; }
function SkillItem({ kind, top, bottom }: { kind: "book" | "document" | "layers" | "handshake" | "people"; top: string; bottom: string }) { return <div><SkillIcon kind={kind} /><span className="skill-label"><strong>{top}</strong><span>{bottom}</span></span></div>; }
function SkillIcon({ kind }: { kind: "book" | "document" | "layers" | "handshake" | "people" }) { const common = { width: 34, height: 34, viewBox: "0 0 34 34", fill: "none", xmlns: "http://www.w3.org/2000/svg", className: "skill-icon", "aria-hidden": true } as const; if (kind === "book") return <svg {...common}><path d="M5 7.5c4.5-2 8.5-1.2 12 1.7v17c-3.5-2.9-7.5-3.7-12-1.7v-17Z" stroke="currentColor" strokeWidth="1.5"/><path d="M29 7.5c-4.5-2-8.5-1.2-12 1.7v17c-3.5-2.9-7.5-3.7-12-1.7v-17Z" stroke="currentColor" strokeWidth="1.5"/><path d="M17 9.2v16.9" stroke="currentColor" strokeWidth="1.5"/></svg>; if (kind === "document") return <svg {...common}><path d="M8 4h12l6 6v20H8V4Z" stroke="currentColor" strokeWidth="1.5"/><path d="M20 4v7h6M12 15h10M12 20h10M12 25h7" stroke="currentColor" strokeWidth="1.5"/></svg>; if (kind === "layers") return <svg {...common}><path d="m17 5 12 7-12 7L5 12l12-7Z" stroke="currentColor" strokeWidth="1.5"/><path d="m7 17 10 6 10-6M7 23l10 6 10-6" stroke="currentColor" strokeWidth="1.5"/></svg>; if (kind === "handshake") return <svg {...common}><path d="m4 12 6-5 6 4 4-3 10 7-5 7-7-5-4 4-10-9Z" stroke="currentColor" strokeWidth="1.5"/><path d="m10 15 4 3 3-3m-7 4 2 2m7-9 4 3" stroke="currentColor" strokeWidth="1.5"/></svg>; return <svg {...common}><circle cx="17" cy="9" r="4" stroke="currentColor" strokeWidth="1.5"/><circle cx="7.5" cy="14" r="3" stroke="currentColor" strokeWidth="1.5"/><circle cx="26.5" cy="14" r="3" stroke="currentColor" strokeWidth="1.5"/><path d="M9 29c.7-5.1 3.3-8 8-8s7.3 2.9 8 8M2 28c.4-3.5 2.2-5.5 5.5-5.5 1.2 0 2.2.3 3 .8M32 28c-.4-3.5-2.2-5.5-5.5-5.5-1.2 0-2.2 0-3 .8" stroke="currentColor" strokeWidth="1.5"/></svg>; }
